name: Maven CI
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
 
    - name: Maven build
      run: mvn -B package --file pom.xml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: artifact
        path: target/test*.jar
      
